# Generated by Django 5.0.4 on 2025-05-20 22:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('worker', 'date')},
        ),
        migrations.RemoveField(
            model_name='worker',
            name='builder',
        ),
        migrations.AddField(
            model_name='worker',
            name='date_of_joining',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='worker',
            name='daily_salary',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='worker',
            name='worker_type',
            field=models.CharField(choices=[('helper', 'Helper'), ('proficient', 'Proficient')], max_length=20),
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='present',
        ),
    ]
